
server:
  port: 8001

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: boardgateway
  cloud:
    gateway:
      globalcore:
        cors-configurations:
          '[/**]':
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
            allowedOrigins:
              - "http://localhost:3000"
            allowedHeaders: "*"

      routes:
        # boardCUD
        # 게시글 수정하기
        - id: boardServiceU
          uri: lb://BOARDSERVICE
          predicates:
            - Path=/board/**
            - Method=PUT
        # 게시글 삭제
        - id: boardServiceD
          uri: lb://BOARDSERVICE
          predicates:
            - Path=/board/**
            - Method=DELETE
        # 게시글 추가
        - id: boardServiceC
          uri: lb://BOARDSERVICE
          predicates:
            - Path=/board/**
            - Method=POST
        # boardR


#   Netty started on port 8001
#  Netty ? ????
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
token:
  secret: user_token

jwt:
  secret_key: asdfghjkl
  expTime: 864000000